# Generated by Django 4.2.5 on 2023-09-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.CharField(default='0.0', max_length=10),
        ),
    ]
